### ISSUE TITLE
Time window for the prices

### ISSUE THREAD

**Issue by stauffenberg2020** [jonkan/Electricity-Prices#14]
Hi,

Thanks for v1.11  :)

As of now the time window is fixed between 12 AM to 12 AM for any day. Will be possible to make the x-axis time window in such a way that the x-axis always starts at current hour and then showing the prices for 24 hours into the future?

**Comment by jonkan** [comment]
Hi, thanks for reaching out!

I want to add a way to display the full next day when tomorrow's prices are available. The use-case being "should I charge the car tonight or tomorrow?". I plan to give it a go when I find the time. Maybe that would fit your needs as well?

**Comment by jonkan** [comment]
The v2.0 version now includes a "Today and Tomorrow" view mode. Thanks for reaching out, I'm closing this issue for now.
