### ISSUE TITLE
Thanks for V2

### ISSUE THREAD

**Issue by stauffenberg2020** [jonkan/Electricity-Prices#17]
Hi Jonas,

Thanks for V2. Even after I have paid, I am still not able to see the day ahead prices in DK1 region. Can you please let me know if this bug can be fixed?

**Comment by jonkan** [comment]
Hi, thanks for reaching out. I know your issues was resolved from your email conversation, but I'll add the response here as well for reference.

The prices of tomorrow are made available sometime after 13:00, the exact time isn't known (to me) so the app is configured to try and fetch them at 13:30. This usually works as far as I have seen.

But you have a point in that, if this is not known, the app is not very user friendly in explaining why tomorrow is not shown before 13:30. I will try to improve/clarify this.
