### ISSUE TITLE
Lockscreen: Optimize axis labels

### ISSUE THREAD

**Issue by naltatis** [jonkan/Electricity-Prices#19]
The y-labels are quite dense. Showing every other number would look more elegant.

The x-labels are dotted. I think it would be fine to just emit the dots in this tight space (0 6 12 18) would be enough.

Maybe also remove the left vertical solid line. Would make it look less blocky.

![image](https://github.com/user-attachments/assets/bd0be392-90ad-4d99-91a7-cf85a9b2076b)

**Comment by jonkan** [comment]
Thank you for reporting! I agree with both of your suggestions. I will try to look into this when I get the time.

**Comment by jonkan** [comment]
Hmm, the reason for the dots is that it adds "Uhr" in the German locale (why?). 
I thought "printing" a date like `Text(date, format: .dateTime.hour(.twoDigits(amPM: .omitted)))` was supposed to always result in exactly two digits. But no, not in German and France :) Oh well. I guess I have to do a ugly DateFormatter hack for this.. 😞  

<img width="342" alt="Skärmavbild 2024-11-22 kl  23 08 33" src="https://github.com/user-attachments/assets/7f0761b4-7c74-47e3-8509-c86ca3fe12e0">
