### ISSUE TITLE
Cent formatting

### ISSUE THREAD

**Issue by naltatis** [jonkan/Electricity-Prices#20]
In Germany the common cent notation is '31,6 ct'.

![image](https://github.com/user-attachments/assets/98501897-ccf5-4df3-bed3-324e0ee64d65)

**Comment by jonkan** [comment]
Ah, thanks for pointing this out. Do you know if that should apply to all Euro regions?

**Comment by naltatis** [comment]
I'm not sure. In our project, I've also done some international electricity price formatting. I also had to do some internet searching and rolled my own currency-specific formatting logic, which may not always correct.

https://github.com/evcc-io/evcc/blob/master/assets/js/mixins/formatter.js#L2-L15

https://github.com/evcc-io/evcc/blob/master/assets/js/mixins/formatter.js#L288

**Comment by jonkan** [comment]
Alright! Ok, so I found this source: https://european-union.europa.eu/document/download/b9fdeae1-dc66-47a7-a902-fb941309e744_hr?filename=publication6336_en.pdf
> There is no official abbreviation for “cent”, but one could reflect on using either “c” or “ct”.

But I'll totally take your word for it and just change to ct.
Thank you for helping me improve the app :)

**Comment by naltatis** [comment]
Interesting. c is extremely uncommon, at least here in Germany 😀
