### ISSUE TITLE
Feature request: View mode for upcoming hours only

### ISSUE THREAD

**Issue by johanFuturice** [jonkan/Electricity-Prices#21]
Simply put: As a user, I want to know only the price of _upcoming_ hours only, because I cannot affect/impact past hours' consumption i.e. I use this app to e.g. plan car charging and similar. 

This view would ideally be the current "Today and Tomorrow" switched into "Now until tomorrow". Or can even be a separate new toggle "Hide past hours" to complement the current views.

**Comment by johanFuturice** [comment]
After testing a few days: Love this new view 🙌 . It takes a (very little) bit to get used to the constantly changing timeframe, as you said, but overall I think this makes the chart more relevant to me at least. I don't really see any need to tweak this one way or the other as it stands now, but will keep using this actively also going forward

**Comment by jonkan** [comment]
Thanks for testing and feedback. Yeah, I like it too. I didn't think the constantly changing X-axis was too bad either.

I think the X-axis labels could be improved, the hours that get labels varies now. But not sure if moving labels, e.g. a label at midnight that follows that prices as the day progresses would be better. That might have its challenges implementation wise as well.. Anyhow, that can be done later, if needed. I think I'll release this soon.

**Comment by jonkan** [comment]
This is now released in v2.7
